# File paths
keystore-path = '/opt/raiden/config/keys'
datadir = '/opt/raiden/data'
password-file = '/opt/raiden/config/passwd'

# Networking
eth-rpc-endpoint = "http://localhost:8545"
network-id = 4321

environment-type = "development"
accept-disclaimer = true
api-address = "0.0.0.0:5001"
matrix-server = "http://localhost"

routing-mode = "pfs"
pathfinding-service-address = "http://localhost:6000"
# Misc
address = "0x517aAD51D0e9BbeF3c64803F86b3B9136641D9ec"

# Log settings
[log-config]
"raiden" = "INFO"
